apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: paperless-ocr
  name: paperless-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: paperless-ocr
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: paperless-ocr
    spec:
      containers:
        - name: gotenberg
          image: gotenberg/gotenberg:7
          args:
            - "gotenberg"
            - "--uno-listener-start-timeout=30s"
            - "--chromium-disable-routes=true"
          securityContext:
            privileged: false
            runAsUser: 1001
          resources:
            limits:
              cpu:    "400m"
              memory: "750Mi"
            requests:
              cpu:    "200m"
              memory: "400Mi"
          ports:
            - containerPort: 3000
        - name: tika
          image: logicalspark/docker-tikaserver:1.28.4
          resources:
            limits:
              cpu:     "500m"
              memory: "750Mi"
            requests:
              cpu:     "200m"
              memory: "350Mi"
          ports:
            - containerPort: 9998
      restartPolicy: Always
status: {}
